export const foodDetails = {
    apple: {
      calories: 52,
      vitamins: "Vitamin C, Vitamin K",
      proteins: 0.3,
      fats: 0.2,
      carbs: 14,
      sugar: 10,
      fiber: 2.4,
      healthBenefits: "Boosts immune system, supports heart health",
      diseasesCured: "Helps prevent cardiovascular disease, diabetes management",
      dietSuitability: "Vegan, Gluten-Free, Low Carb, Diabetic-Friendly",
      healthWarnings: "Can cause allergic reactions in some people",
      seasonality: "Available year-round",
      cookingMethods: "Best consumed raw, can be baked or juiced",
      substitutes: "Pears, peaches",
      environmentalImpact: "Low carbon footprint",
      regionalUses: "Common in American and European desserts",
    },
    Rice: {
      calories: 41,
      vitamins: "Vitamin A, Vitamin K",
      proteins: 0.9,
      fats: 0.2,
      carbs: 10,
      sugar: 4.7,
      fiber: 2.8,
      healthBenefits: "Good for vision, lowers cholesterol",
      diseasesCured: "Helps reduce the risk of cancer, supports eye health",
      dietSuitability: "Vegan, Gluten-Free, Low Carb",
      healthWarnings: "Excessive consumption may cause carotenemia (skin yellowing)",
      seasonality: "Best in winter but available year-round",
      cookingMethods: "Best consumed raw, roasted, or in soups",
      substitutes: "Sweet potatoes, squash",
      environmentalImpact: "Low water usage in production",
      regionalUses: "Widely used in Asian and European cuisines",
    }
  };
  